spring.application.name=QuickDish

spring.datasource.url=jdbc:postgresql://localhost:5432/QuickDish
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.username=postgres
spring.datasource.password=Ashish
spring.jpa.open-in-view=true

server.servlet.context-path=/api/v1
#frontend.url=http://localhost:8080

jwt.SecretKey=ahggnhojfgbgugikajljoighnafpieorugowei8adfyrfiukrg78fega87gregraewoerjs



