spring.application.name=QuickDish

spring.datasource.url=jdbc:postgresql://localhost:5432/Fastfoody
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=postgres
spring.datasource.password=Ashish
spring.jpa.open-in-view=true

server.servlet.context-path=/api/v1

#jwt.SecretKey =ahggnhojfgajljoighnafpieorugowei8adfyrfiukrg78fega87gregraewoerjs



